steps:
  - name: "gcr.io/cloud-builders/go"
    id: Test
    args:
      - "test"
      - "./..."
    env: ["PROJECT_ROOT=${_ROOT}"]
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    entrypoint: sh
    args:
      - "-c"
      - "cd ${_ROOT} && docker build -t ${_TAG_NAME} ."
    env:
      - "PROJECT_ROOT=${_ROOT}"
