steps:
  - name: "gcr.io/cloud-builders/go"
    id: Test
    args:
      - "test"
      - "./..."
    env: ["PROJECT_ROOT=${_ROOT}"]
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    entrypoint: sh
    args:
      - "-c"
      - "cd ${_ROOT} && docker build -t gcr.io/$PROJECT_ID/$REPO_NAME/${_ROOT}:${SHORT_SHA} ."

  - name: "gcr.io/cloud-builders/gcloud"
    id: Copy ssh key
    args:
      - kms
      - decrypt
      - --ciphertext-file=id_rsa.enc
      - --plaintext-file=/root/.ssh/id_rsa
      - --location=global
      - --keyring=cloud-build-keyring
      - --key=github-key
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    id: Prepare git clone
    entrypoint: "bash"
    args:
      - "-c"
      - |
        chmod 600 /root/.ssh/id_rsa
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_rsa
        EOF
        mv known_hosts /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    id: Commit env repository and push
    entrypoint: "bash"
    args:
      - "-c"
      - |
        git clone git@github.com:tamanobi/env-gitops-sample-with-cloud-build
        cd env-gitops-sample-with-cloud-build
        echo 'aaaaaa' >> README.md
        git commit -am'yay'
        git push origin master
    volumes:
      - name: "ssh"
        path: /root/.ssh
