steps:
  - name: 'gcr.io/cloud-builders/go'
    id: Test
    args:
      - 'test'
      - './...'
    env: ['PROJECT_ROOT=${_ROOT}']
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    entrypoint: sh
    args:
      - '-c'
      - 'cd ${_ROOT} && docker build -t gcr.io/$PROJECT_ID/$REPO_NAME/${_ROOT}:${SHORT_SHA} .'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Copy ssh key
    args:
      - kms
      - decrypt
      - --ciphertext-file=id_cloud_build.enc
      - --plaintext-file=/root/.ssh/id_rsa
      - --location=global
      - --keyring=cloud-build-keyring
      - --key=github-key
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    id: Prepare git clone
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 600 /root/.ssh/id_rsa
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_rsa
        EOF
        mv known_hosts /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    id: Commit env repository and push
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone git@github.com:tamanobi/env-gitops-sample-with-cloud-build
        cd env-gitops-sample-with-cloud-build

        git config --local user.email "hogehoge@example.com"
        git config --local user.name "Cloud Build"

        echo "gcr.io/$PROJECT_ID/$REPO_NAME/${_ROOT}:${SHORT_SHA}" > "${_ROOT}"

        git checkout -b feature/update-container-image-tag-${SHORT_SHA}
        git add "${_ROOT}"
        git commit -m'Update container image tag by cloud build'

        git push origin feature/update-container-image-tag-${SHORT_SHA}
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    id: Create pull-request
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -sSL https://github.com/github/hub/releases/download/v2.12.8/hub-linux-amd64-2.12.8.tgz | tar -xzf -
        GITHUB_TOKEN="${_GITHUB_TOKEN}" ./hub-linux-amd64-2.12.8/bin/hub pull-request \
          -b master \
          -h feature/update-container-image-tag-${SHORT_SHA} \
          -m"Update container image tag by cloud build"
    volumes:
      - name: 'ssh'
        path: /root/.ssh
